#Format: [["dimension_1", temperature1, *units], ["dimension_2", temperature2, *units]... etc]
#Common dimension IDs: minecraft:overworld, minecraft:the_nether, minecraft:the_end
[Dimensions]
	#Applies an offset to the world's temperature across an entire dimension
	"Dimension Temperature Offsets" = [["minecraft:the_nether", 0.7], ["minecraft:the_end", -0.1]]
	#Defines the temperature of a dimension, overriding all other biome and dimension temperatures/settings
	"Dimension Temperatures" = []

#Format: [["biome_1", <low-temp>, <high-temp>, <*units>], ["biome_2", <low-temp>, <high-temp>, <*units>]... etc]
#low-temp: The temperature of the biome at midnight
#high-temp: The temperature of the biome at noon
#units: Optional. The units of the temperature ("C" or "F". Defaults to MC units)
[Biomes]
	#Applies an offset to the temperature of a biome
	"Biome Temperature Offsets" = []
	#Defines the temperature of a biome, overriding the biome's default temperature
	"Biome Temperatures" = [["minecraft:soul_sand_valley", 53, 53, "F"], ["minecraft:old_growth_birch_forest", 58, 72, "F"], ["minecraft:river", 60, 70, "F"], ["minecraft:swamp", 72, 84, "F"], ["minecraft:savanna", 70, 95, "F"], ["minecraft:savanna_plateau", 76, 98, "F"], ["minecraft:windswept_savanna", 67, 90, "F"], ["minecraft:taiga", 44, 62, "F"], ["minecraft:snowy_taiga", 19, 48, "F"], ["minecraft:old_growth_pine_taiga", 48, 62, "F"], ["minecraft:old_growth_spruce_taiga", 48, 62, "F"], ["minecraft:desert", 48, 115, "F"], ["minecraft:stony_shore", 50, 64, "F"], ["minecraft:snowy_beach", 38, 52, "F"], ["minecraft:snowy_slopes", 24, 38, "F"], ["minecraft:windswept_forest", 48, 66, "F"], ["minecraft:frozen_peaks", 15, 33, "F"], ["minecraft:warm_ocean", 67, 76, "F"], ["minecraft:deep_frozen_ocean", 56, 65, "F"], ["minecraft:jungle", 76, 87, "F"], ["minecraft:bamboo_jungle", 76, 87, "F"], ["minecraft:badlands", 84, 120, "F"], ["minecraft:wooded_badlands", 80, 108, "F"], ["minecraft:eroded_badlands", 88, 120, "F"], ["minecraft:deep_dark", 63, 63, "F"]]

[Blocks]
	# Format:
	# [["block-ids", <temperature>, <range>, <*units>, <*max effect>, <*predicates>, <*nbt>, <*temperature-limit>], [etc...], [etc...]]
	# * = Optional
	# 
	# Arguments:
	# block-ids: Multiple IDs can be used by separating them with commas (i.e: "minecraft:torch,minecraft:wall_torch")
	# temperature: The temperature of the block, in Minecraft units
	# *falloff: The block is less effective as distance increases
	# *max effect: The maximum temperature change this block can cause to a player (even with multiple blocks)
	# *predicates: The state that the block has to be in for the temperature to be applied (i.e. lit=true).
	# - (Multiple predicates can be used by separating them with commas [i.e. "lit=true,waterlogged=false"])
	# *nbt: The NBT data that the block must have for the temperature to be applied.
	# *temperature-limit: The maximum world temperature at which this block temp will be effective.
	# - (Represents the minimum temp if the block temp is negative)
	"Block Temperatures" = [["cold_sweat:boiler", 0.27, 7, "mc", 0.88, "lit=true", "", 4], ["cold_sweat:icebox", -0.27, 7, "mc", 0.88, "frosted=true", "", 0], ["minecraft:fire", 0.476, 7, "mc", 0.9, "", "", 8], ["#minecraft:campfires", 0.476, 7, "mc", 0.9, "lit=true", " ", 8], ["minecraft:magma_block", 0.25, 3, "mc", 1.0], ["minecraft:lava_cauldron", 0.5, 7, "mc", 1.5], ["minecraft:ice", -0.15, 4, "mc", 0.6, "", "", -0.7], ["minecraft:packed_ice", -0.25, 4, "mc", 1.0, "", "", -0.7], ["minecraft:blue_ice", -0.35, 4, "mc", 1.4, "", "", -0.7], ["#minecraft:ice", -0.15, 4, "mc", 0.6, "", "", -0.7]]
	#The maximum range of blocks' area of effect
	#Note: This will not change anything unless blocks are configured to utilize the expanded range
	#This value is capped at 16 for performance reasons
	# Default: 7
	# Range: 1 ~ 16
	"Block Range" = 7
	#When set to true, uses Cold Sweat's temperature system to determine water freezing behavior
	"Custom Freezing Behavior" = true
	#When set to true, modifies ice blocks to be harvestable with a pickaxe
	"Custom Ice Drops" = true

[Misc]
	#A temperature offset applied when the sky is overcast
	#Format: [offset, *units]
	"Overcast Temperature Offset" = [-0.35, "mc"]
	#Overrides the world temperature when the player is within this structure
	#Format: [["structure_1", temperature1, *units], ["structure_2", temperature2, *units]... etc]
	#(* = optional)
	"Structure Temperatures" = [["minecraft:igloo", 65, "F"]]
	#Offsets the world temperature when the player is within this structure
	#Format: [["structure_1", offset1, *units], ["structure_2", offset2, *units]... etc]
	#(* = optional)
	"Structure Temperature Offsets" = []
	#List of blocks that will allow the player to sleep on them, regardless of the "Prevent Sleep When in Danger" setting
	#Use this list if the player is not getting the temperature effect from sleeping on particular blocks
	"Sleep Check Override Blocks" = []
	#When set to true, players cannot sleep if they are cold or hot enough to die
	"Check Sleeping Conditions" = true
	#Converts damage dealt by Soul Fire to cold damage (default: true)
	#Does not affect the block's temperature
	"Cold Soul Fire" = true

["Thermal Sources"]
	#How effective thermal sources are at normalizing temperature
	# Default: 0.75
	# Range: 0.0 ~ 1.0
	"Thermal Source Strength" = 0.75
	#List of additional blocks that thermal sources can spread through
	#Use this list if thermal sources aren't spreading through particular blocks that they should
	"Thermal Source Spread Whitelist" = ["cold_sweat:hearth_bottom", "minecraft:iron_bars", "#minecraft:leaves"]
	#List of additional blocks that thermal sources spread through
	#Use this list if thermal sources are spreading through particular blocks that they shouldn't
	"Thermal Source Spread Blacklist" = ["minecraft:water"]

	["Thermal Sources".Hearth]
		#Allows the hearth to automatically turn on/off based on nearby players' temperature
		#If false, it turns on/off by redstone signal instead
		"Automatic Hearth" = false
		#The distance the hearth's air will travel from a source, like the hearth itself or the end of a pipe
		# Default: 20
		# Range: > 0
		"Hearth Range" = 20
		#The maximum distance that air can be piped away from the hearth
		# Default: 96
		# Range: > 0
		"Max Hearth Range" = 96
		#The maximum volume of the hearth's area of effect
		# Default: 12000
		# Range: > 1
		"Hearth Volume" = 12000
		#The time it takes for the hearth to be fully functional after being placed
		# Default: 1200
		# Range: > 0
		"Hearth Warm-Up Time" = 1200
		#The maximum amount of insulation that the hearth can provide
		# Default: 10
		# Range: 0 ~ 10
		"Hearth Effect Strength" = 10
		#How often the hearth consumes fuel (in ticks)
		#Lower numbers mean fuel is consumed faster. Setting to 0 disables fuel consumption
		# Default: 40
		# Range: > 0
		"Hearth Fuel Consumption Interval" = 40

	["Thermal Sources".Boiler]
		#Allows the boiler to automatically turn on/off based on nearby players' temperature
		#If false, it turns on/off by redstone signal instead
		"Automatic Boiler" = false
		#The distance the boiler's air will travel from a source, like the boiler itself or the end of a pipe
		# Default: 16
		# Range: > 0
		"Boiler Range" = 16
		#The maximum distance that air can be piped away from the boiler
		# Default: 96
		# Range: > 0
		"Max Boiler Range" = 96
		#The maximum volume of the boiler's area of effect
		# Default: 2000
		# Range: > 1
		"Boiler Volume" = 2000
		#The time it takes for the boiler to be fully functional after being placed
		# Default: 1200
		# Range: > 0
		"Boiler Warm-Up Time" = 1200
		#The maximum amount of insulation that the boiler can provide
		# Default: 5
		# Range: 0 ~ 10
		"Boiler Warmth Strength" = 5
		#How often the boiler consumes fuel (in ticks)
		#Lower numbers mean fuel is consumed faster. Setting to 0 disables fuel consumption
		# Default: 40
		# Range: > 0
		"Boiler Fuel Consumption Interval" = 40

	["Thermal Sources".Icebox]
		#Allows the icebox to automatically turn on/off based on nearby players' temperature
		#If false, it turns on/off by redstone signal instead
		"Automatic Icebox" = false
		#The distance the icebox's air will travel from a source, like the icebox itself or the end of a pipe
		# Default: 16
		# Range: > 0
		"Icebox Range" = 16
		#The maximum distance that air can be piped away from the icebox
		# Default: 96
		# Range: > 0
		"Max Icebox Range" = 96
		#The maximum volume of the icebox's area of effect
		# Default: 2000
		# Range: > 1
		"Icebox Volume" = 2000
		#The time it takes for the icebox to be fully functional after being placed
		# Default: 1200
		# Range: > 0
		"Icebox Warm-Up Time" = 1200
		#The maximum amount of insulation that the icebox can provide
		# Default: 5
		# Range: 0 ~ 10
		"Icebox Chill Strength" = 5
		#How often the icebox consumes fuel (in ticks)
		#Lower numbers mean fuel is consumed faster. Setting to 0 disables fuel consumption
		# Default: 40
		# Range: > 0
		"Icebox Fuel Consumption Interval" = 40

#Format: [season-start, season-mid, season-end, *units]
#First 3 parameters: The temperature offset at the start, middle, and end of the season
#units: (Optional) The unit of temperature (C, F, or MC)
#Applied as an offset to the world's temperature
["Season Temperatures"]
	Summer = [0.4, 0.6, 0.4]
	Autumn = [0.2, 0, -0.2]
	Winter = [-0.4, -0.6, -0.4]
	Spring = [-0.2, 0, 0.2]
